package de.fayard.refreshVersions.core

import de.fayard.refreshVersions.core.internal.Case
import de.fayard.refreshVersions.core.internal.Deps
import de.fayard.refreshVersions.core.internal.MEANING_LESS_NAMES
import de.fayard.refreshVersions.core.internal.checkModeAndNames
import de.fayard.refreshVersions.core.internal.computeUseFqdnFor
import de.fayard.refreshVersions.core.internal.findDependencies
import de.fayard.refreshVersions.core.internal.OutputFile
import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.tasks.TaskAction
import org.gradle.util.GradleVersion

@Suppress("UnstableApiUsage")
open class VersionsCatalogTask : DefaultTask() {

    @TaskAction
    fun checkGradleVersion() {
        if (currentGradleVersion < versionWithVersionsCatalog) {
            throw GradleException(
                """
                |Gradle versions catalogs are not supported in $currentGradleVersion
                |Upgrade Gradle with this command
                |     ./gradlew wrapper --gradle-version $versionWithVersionsCatalog
            """.trimMargin()
            )
        }
    }


    @TaskAction
    fun addMissingEntries() {
        addMissingEntriesInVersionsProperties(project)
    }


    @TaskAction
    fun taskUpdateVersionsCatalog() {
        val catalog = OutputFile.GRADLE_VERSIONS_CATALOG

        val allDependencies = project.findDependencies()
        val resolvedUseFqdn: List<String> = computeUseFqdnFor(
            libraries = allDependencies,
            configured = emptyList(),
            byDefault = MEANING_LESS_NAMES
        )
        val deps: Deps = allDependencies.checkModeAndNames(resolvedUseFqdn, Case.camelCase)
        val currentText = if (catalog.existed) catalog.readText(project) else ""
        val newText = versionsCatalog(deps, currentText)
        catalog.writeText(newText, project)
        catalog.logFileWasModified()
    }

    companion object {
        val currentGradleVersion = GradleVersion.current()
        val versionWithVersionsCatalog = GradleVersion.version("7.4")

        internal fun parseTomlInSection(toml: String): Map<String, String> {
            val result = mutableMapOf<String, StringBuilder>()
            result["root"] = StringBuilder()
            var current: StringBuilder = result["root"]!!
            val lines = toml.lines()
            for ((index, line) in lines.withIndex()) {
                val trimmed = line.trim()
                val isSectionHeader = trimmed.startsWith("[") && trimmed.endsWith("]")
                if (isSectionHeader) {
                    val sectionName = trimmed.removePrefix("[").removeSuffix("]")
                    result[sectionName] = StringBuilder()
                    current = result[sectionName]!!
                } else {
                    current.append(line)
                    if (index != lines.lastIndex) current.append("\n")
                }
            }
            return result.mapValues { it.value.toString() }
        }

        internal fun tomlSectionsToString(sections: Map<String, String>): String = buildString {
            for ((header, content) in sections) {
                if (header != "root") append("[$header]\n")
                append(content)
            }
        }

        internal fun versionsCatalog(deps: Deps, currentText: String): String {
            val sections = parseTomlInSection(currentText).toMutableMap()
            if (sections["root"].isNullOrBlank()) {
                sections["root"] = "## Generated by $ ./gradlew refreshVersionsCatalog\n\n"
            }
            sections["libraries"] = versionsCatalogLibraries(deps)
            return tomlSectionsToString(sections)
        }

        internal fun versionsCatalogLibraries(deps: Deps) = buildString {
            append('\n')
            deps.libraries.forEach {
                append(deps.names[it])
                append(" = \"")
                append(it.groupModuleUnderscore())
                append('"')
                append("\n")
                append("\n")
            }
            append("\n")
        }
    }
}

