import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val androidx_core_core: String = "androidx.core:core:_"

    public const val guava: String = "com.google.guava:guava:_"

    public const val guice: String = "com.google.inject:guice:_"

    public const val okhttp: String = "com.squareup.okhttp3:okhttp:_"

    public const val okhttp_urlconnection: String = "com.squareup.okhttp3:okhttp-urlconnection:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val kotest_runner_junit4: String = "io.kotest:kotest-runner-junit4:_"

    public const val junit: String = "junit:junit:_"

    public const val log4j_bom: String = "org.apache.logging.log4j:log4j-bom:_"

    public const val log4j_jul: String = "org.apache.logging.log4j:log4j-jul"

    public const val log4j_slf4j_impl: String = "org.apache.logging.log4j:log4j-slf4j-impl"

    public const val poi: String = "org.apache.poi:poi:_"

    public const val poi_ooxml: String = "org.apache.poi:poi-ooxml:_"

    public const val gradle_hello_world_plugin: String = "org.gradle:gradle-hello-world-plugin:_"

    public const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:_"

    public const val kotlin_script_runtime: String = "org.jetbrains.kotlin:kotlin-script-runtime"

    public const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:_"

    public const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    public const val org_jetbrains_kotlinx_benchmark_gradle_plugin: String =
            "org.jetbrains.kotlinx.benchmark:org.jetbrains.kotlinx.benchmark.gradle.plugin:_"

    public const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    public const val kotlinx_coroutines_jdk8: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:_"

    public const val mongo_java_driver: String = "org.mongodb:mongo-java-driver:_"
}
