/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val com_squareup_okhttp3: String = "4.2.0"

    const val org_jetbrains_kotlin: String = "1.3.50"

    const val org_mongodb_mongo_java_driver: String = "3.11.0"

    const val com_google_inject_guice: String = "2.0"

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String = "1.3.50"

    const val com_gradle_build_scan_gradle_plugin: String = "2.4.2"

    const val guava: String = "15.0"

    /**
     * Current version: "5.6.2"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6.2"
}
