# pip install -r docs/requirements.txt
# mkdocs serve

site_name: gradle refreshVersions
site_url: https://jmfayard.github.io/refreshVersions/
repo_name: refreshVersions
repo_url: https://github.com/jmfayard/refreshVersions
site_description: "Life is too short to google for dependencies and versions"
site_author: jmfayard LouisCAD
remote_branch: gh-pages
edit_uri: "https://github.com/jmfayard/refreshVersions/edit/release/docs"

extra:
  link:
    playground: https://github.com/LouisCAD/kotlin-libraries-playground
    site: https://jmfayard.github.io/refreshVersions
    github: https://github.com/jmfayard/refreshVersions
    master: https://github.com/jmfayard/refreshVersions/blob/main
    issues: https://github.com/jmfayard/refreshVersions/issues
    gradlePluginPortal: https://plugins.gradle.org/plugin/de.fayard.refreshVersions
    slack: https://app.slack.com/client/T09229ZC6/CP5659EL9
  version:
    gradle: 6.7
    refreshVersions: '0.9.7'
    refreshVersionsDev: '0.9.7-dev-001'
  keyboard_shortcuts:
    find_actions: <kbd>ctrl</kbd>/<kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>A</kbd>

copyright: 'Copyright &copy; 2020 jmfayard'

theme:
  name: 'material'
## TODO: we need a logo
#  favicon: images/icon-square.png
#  logo: images/icon-square.png
  palette:
    primary: 'teal'
    accent: 'white'

extra_css:
  - 'app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tabbed
  - tables

nav:
  - 'Overview': index.md
  - 'Setup': setup.md
  - 'Add Dependencies': add-dependencies.md
  - 'Update Dependencies': update-dependencies.md
#  - 'Gradle buildSrcVersions': gradle-buildsrcversions.md
  - 'Migration': migration.md
  - 'FAQ': faq.md
  - 'Change Log': CHANGELOG.md
  - 'Contributing':
    - 'Code of Conduct': contributing/code_of_conduct.md
    - 'Improving docs': contributing/improving-docs.md
    - 'Dev environment': contributing/dev-env.md
    - 'Dependency notations': contributing/dependency-notations-updates.md

plugins:
  - search
  - markdownextradata: {}
