# pip install -r docs/requirements.txt
# mkdocs serve

site_name: gradle refreshVersions
site_url: https://jmfayard.github.io/refreshVersions/
repo_name: refreshVersions
repo_url: https://github.com/jmfayard/refreshVersions
site_description: "Life is too short to google for dependencies and versions"
site_author: jmfayard LouisCAD
remote_branch: gh-pages
edit_uri: "https://github.com/Splitties/refreshVersions/edit/release/docs"

extra:
  link:
    playground: https://github.com/LouisCAD/kotlin-libraries-playground
    site: https://splitties.github.io/refreshVersions
    github: https://github.com/Splitties/refreshVersions
    master: https://github.com/Splitties/refreshVersions/blob/main
    issues: https://github.com/Splitties/refreshVersions/issues
    gradlePluginPortal: https://plugins.gradle.org/plugin/de.fayard.refreshVersions
    slack: https://app.slack.com/client/T09229ZC6/CP5659EL9
  version:
    gradle: 8.5
    refreshVersions: '0.60.5'
    snapshot: '0.60.6-SNAPSHOT'
  keyboard_shortcuts:
    find_actions: <kbd>ctrl</kbd>/<kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>A</kbd>

copyright: 'Copyright &copy; 2020-2024 jmfayard - Louis CAD'

theme:
  name: 'material'
## TODO: we need a logo
#  favicon: images/icon-square.png
#  logo: images/icon-square.png
  palette:
    primary: 'teal'
    accent: 'white'

extra_css:
  - 'app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - admonition

nav:
  - 'Overview': index.md
  - 'Setup': setup.md
  - 'Migrate': migrate.md
  - 'Add Dependencies': add-dependencies.md
  - 'Built-in Dependency Notations': dependency-notations.md
  - 'Update Dependencies': update-dependencies.md
  - 'RefreshVersionsBot': refreshversions-bot.md
  - 'Change Log': CHANGELOG.md
  - 'Contributing':
    - 'Before you contribute': contributing/before-you-contribute.md
    - 'Improving docs': contributing/improving-docs.md
    - 'Submitting issues': contributing/submitting-issues.md
    - 'Dev environment': contributing/submitting-prs/dev-env.md
    - 'Development process': contributing/submitting-prs/dev-process.md
    - 'Dependency notations': contributing/submitting-prs/dependency-notations-updates.md
  - 'Bonus: Gradle tips and tricks': gradle-tips.md
  - 'legacy':
      - 'Gradle buildSrcVersions': gradle-buildsrcversions.md

plugins:
  - search
  - markdownextradata: {}
