// plugin.de.fayard.refreshVersions (aka refreshVersions)
:gradle_version: 6.4.1
:repo: jmfayard/refreshVersions
:github: https://github.com/{repo}
:plugin_gradle_portal: https://plugins.gradle.org/plugin/de.fayard.refreshVersions
:contributors_badge: image:https://www.codetriage.com/jmfayard/buildsrcversions/badges/users.svg["Code Triage",link="https://www.codetriage.com/jmfayard/buildsrcversions"]
:gradle_kotlin_dsl:	https://github.com/gradle/kotlin-dsl
:slack_url: https://app.slack.com/client/T09229ZC6/CP5659EL9
:slack_image: https://img.shields.io/static/v1?label=kotlinlang&message=gradle-refresh-versions&color=brightgreen&logo=slack
:slack_badge: image:{slack_image}["Kotlinlang Slack", link="{slack_url}"]
:gradle_guide_new:	https://guides.gradle.org/creating-new-gradle-builds
:gradle_guide_buildlogic:	https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/
:issues: https://github.com/jmfayard/refreshVersions/issues
:master: https://github.com/jmfayard/refreshVersions/blob/master
:badge_mit: image:https://img.shields.io/github/license/mashape/apistatus.svg["GitHub",link="{github}/blob/master/LICENSE.txt"]
:image_refreshVersions_version: https://img.shields.io/maven-metadata/v/https/plugins.gradle.org/m2/de.fayard/refreshVersions/de.fayard.refreshVersions.gradle.plugin/maven-metadata.xml.svg
:badge_refreshVersions_version: image:{image_refreshVersions_version}?label=refreshVersions["refreshVersions latest release on Gradle plugin portal",link="{plugin_gradle_portal}"]

= refreshVersions

*End the dependency hell in minutes.*

{badge_refreshVersions_version} {slack_badge} {contributors_badge} {badge_mit}

== What

The `refreshVersions` plugin targets *all kinds of Gradle projects*, including the following:

- Kotlin Multiplatform
- Android
- Kotlin/JS, Kotlin/JVM, Kotlin/Native
- Java

The `refreshVersions` Gradle plugin brings the following benefits:

1. *Centralizes dependencies versions* (very useful in multi-module projects)
2. *Shows available updates in seconds*
3. *Allows applying the available updates with minimal effort*
4. *Makes discovering select dependencies a breeze with autocomplete in the IDE**

== Why (the problem this project solves)

Gradle multi-module projects are on the rise because of how it enforces code decoupling,
which is a good thing for maintenance and inevitable changes.

Unfortunately, that means the number of build files (`build.gradle[.kts]`) are multiplied,
which makes upgrading the dependencies versions where significantly more tedious as you now
need to open, edit and check more files.

Also, some library vendors like Google are publishing artifacts with different versions
(AndroidX, Google Play Services and Firebase, just to name a few). AndroidX for example has
about 70 different families with different versions overall.

We saw this made developers to update the dependencies less and less often, effectively
leading to legacy accumulation, or even projects abandon.

We firmly believe the *modularization benefits should not be hindered by these drawbacks*.
That's how refreshVersions was born.

We want discovery of dependencies updates to be as quick as possible, we want applying these
updates be as quick as possible through the whole codebase, and we want to remove the human
error factor in dependencies declaration and update.
That's exactly what `refreshVersions` can already do today in your project.

== Usage
=== Adding to an existing project

_Note: Only Gradle 6+ is supported at the moment, because it allows for simpler setup._

_Updating Gradle is usually a good idea. You get fewer bugs, more features and more build speed, and it's as simple as this:_

`$ ./gradlew wrapper --gradle-version {gradle_version}`

==== Step 1: Adding the plugin

Add the following snippet in your project's root `settings.gradle(.kts)` file:

[source,kts,subs=attributes]
----
// settings.gradle.kts
import de.fayard.refreshVersions.bootstrapRefreshVersions

// Here you might have some pluginManagement block:
pluginManagement {
    //...
}

buildscript {
    repositories { gradlePluginPortal() }
    dependencies.classpath("de.fayard.refreshVersions:refreshVersions:0.9.5")
}

bootstrapRefreshVersions()
----

==== Step 2: Migrating the dependencies versions declaration place

Run the following command on the root project:

`./gradlew migrateToRefreshVersionsDependenciesConstants --console=plain`

This Gradle task is interactive.
It will walk you through every module of your Gradle project, assisting you in replacing every hardcoded dependency version by the
version placeholder (`_`), and an entry in the `versions.properties` file, for every configuration.

_Note that while this Gradle task cannot break your build, it is experimental.
We are aware its UX can be improved, and we have plans to work on it before the 1.0 release._

=== Find available updates (aka. refreshVersions)

Run the `refreshVersions` gradle task on the root project:

`./gradlew refreshVersions`

_(It usually takes less than 10 seconds to execute on relatively big projects.)_

Open the `versions.properties` file and see the available updates added as comments.

=== Apply updates

Applying updates is done in the `versions.properties` file.

1. Put the caret before or after the `=` symbol on the available update line.
2. Hold shift to start text selection, press the up arrow key and release shift.
3. Press the backspace/delete key.
4. If you're in an IDE, sync Gradle changes to see new dependencies versions.

== Using a development version

In case you want to try new features or get a fix for a bug that affects a project you work on,
before they make it into a release, you can use a development version.

To do so, in your `settings.gradle.kts` file(s), ensure the `buildscript` has this maven repository:
`https://dl.bintray.com/jmfayard/maven`, and a valid dev version is set, as such:

[source,kts,subs=attributes]
----
buildscript {
    repositories { maven(url = "https://dl.bintray.com/jmfayard/maven") } // <- here
    dependencies.classpath("de.fayard.refreshVersions:refreshVersions:0.9.5-dev-002")
}
----

You can find the published development versions by searching in the recent commits on the develop
branch, they start with "Dev version".

== Bonus: tips for your Gradle projects

Good documentation can also help you upgrade an old project to the latest and greatest.

I have a series of articles called `Built with Gradle`:

- https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg[Use the Build Scan ! The one Gradle trick that supersedes all the others]
- https://dev.to/jmfayard/configuring-gradle-with-gradle-properties-211k[Configuring Gradle with the `gradle.properties` file]
- https://dev.to/jmfayard/how-kotlin-makes-editing-your-gradle-build-less-frustrating-232l[How Kotlin makes editing your Gradle build less frustrating]

To get the future tips and informative articles, you can follow me on https://dev.to/jmfayard[dev.to].

== Authors
- https://github.com/jmfayard[Jean-Michel Fayard]
- https://github.com/LouisCAD[Louis CAD]

== FAQ

Questions? {issues}[Look at the existing issues], then ask your own.

For special requests (not issues), you can also reach us out on https://slack.kotl.in[Kotlin's Slack] in the {slack_url}[#gradle-refresh-versions] channel.

== Release notes

See the link:CHANGELOG.md[CHANGELOG.md] file.

== Contributing

- This project is licensed under the MIT License. See link:LICENSE.txt[LICENSE.txt]
- Explain your use case and start the discussion before your submit a pull-request
- {master}/CONTRIBUTING.md[*CONTRIBUTING.md*] describes the process for submitting pull requests.
