// plugin.de.fayard.refreshVersions (aka refreshVersions)
:ext-relative: {outfilesuffix}
:repo: jmfayard/refreshVersions
:github: https://github.com/{repo}
:plugin_gradle_portal: https://plugins.gradle.org/plugin/de.fayard.refreshVersions
:contributors_badge: image:https://www.codetriage.com/jmfayard/buildsrcversions/badges/users.svg["Code Triage",link="https://www.codetriage.com/jmfayard/buildsrcversions"]
:gradle_kotlin_dsl:	https://github.com/gradle/kotlin-dsl
:slack_url: https://app.slack.com/client/T09229ZC6/CP5659EL9
:slack_image: https://img.shields.io/static/v1?label=kotlinlang&message=gradle-refresh-versions&color=brightgreen&logo=slack
:slack_badge: image:{slack_image}["Kotlinlang Slack", link="{slack_url}"]
:gradle_guide_new: https://guides.gradle.org/creating-new-gradle-builds
:gradle_guide_buildlogic: https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/
:issues: https://github.com/jmfayard/refreshVersions/issues
:master: https://github.com/jmfayard/refreshVersions/blob/master
:badge_mit: image:https://img.shields.io/github/license/mashape/apistatus.svg["GitHub",link="{github}/blob/master/LICENSE.txt"]
:image_refreshVersions_version: https://img.shields.io/maven-metadata/v/https/plugins.gradle.org/m2/de.fayard/refreshVersions/de.fayard.refreshVersions.gradle.plugin/maven-metadata.xml.svg
:badge_refreshVersions_version: image:{image_refreshVersions_version}?label=refreshVersions["refreshVersions latest release on Gradle plugin portal",link="{plugin_gradle_portal}"]

= refreshVersions

*End the dependency hell in minutes.*

{badge_refreshVersions_version} {slack_badge} {contributors_badge} {badge_mit}

== What

The `refreshVersions` plugin targets *all kinds of Gradle projects*, including the following:

- Kotlin Multiplatform
- Android
- Kotlin/JS, Kotlin/JVM, Kotlin/Native
- Java

The `refreshVersions` Gradle plugin brings the following benefits:

1. *Centralizes dependencies versions* (very useful in multi-module projects)
2. *Shows available updates* _in seconds_
3. *Allows applying the available updates* _with minimal effort_
4. *Brings autocomplete for select dependencies* (you can add yours too)

== Why (the problem this project solves)

Gradle multi-module projects are on the rise because of how it enforces code decoupling,
which is a good thing for maintenance and inevitable changes.

Unfortunately, that means the number of build files (`build.gradle[.kts]`) are multiplied,
which makes upgrading the dependencies versions where significantly more tedious as you now
need to open, edit and check more files.

Also, some library vendors like Google are publishing artifacts with different versions
(AndroidX, Google Play Services and Firebase, just to name a few). AndroidX for example has
about 70 different families with different versions overall.

We saw this made developers to update the dependencies less and less often, effectively
leading to legacy accumulation (a form of technical debt), or even projects abandon.

We firmly believe the *modularization benefits should not be hindered by these drawbacks*.
That's how refreshVersions was born.

We want discovery of dependencies updates to be as quick as possible, we want applying these
updates be as quick as possible through the whole codebase, and we want to remove the human
error factor in dependencies declaration and update.
That's exactly what `refreshVersions` can already do today in your project.

== How

link:docs/Setting-up{ext-relative}[The short Setting-up guide is here].

Once setup, you just need to run the `refreshVersions` Gradle task
and apply the updates you want in the `versions.properties` file.

The link:docs/Usage{ext-relative}}[full usage guide (with screenshots) is here].

== Bonus: tips for your Gradle projects

Good documentation can also help you upgrade an old project to the latest and greatest.

I have a series of articles called `Built with Gradle`:

- https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg[Use the Build Scan ! The one Gradle trick that supersedes all the others]
- https://dev.to/jmfayard/configuring-gradle-with-gradle-properties-211k[Configuring Gradle with the `gradle.properties` file]
- https://dev.to/jmfayard/how-kotlin-makes-editing-your-gradle-build-less-frustrating-232l[How Kotlin makes editing your Gradle build less frustrating]

To get the future tips and informative articles, you can follow me on https://dev.to/jmfayard[dev.to].

== Authors
- https://github.com/jmfayard[Jean-Michel Fayard]
- https://github.com/LouisCAD[Louis CAD]

== FAQ

Questions? {issues}[Look at the existing issues], then ask your own.

For special requests (not issues), you can also reach us out on https://slack.kotl.in[Kotlin's Slack] in the {slack_url}[#gradle-refresh-versions] channel.

== Release notes

See the link:CHANGELOG.md[CHANGELOG.md] file.

== Contributing

- This project is licensed under the MIT License. See link:LICENSE.txt[LICENSE.txt]
- Explain your use case and start the discussion before your submit a pull-request
- {master}/CONTRIBUTING.md[*CONTRIBUTING.md*] describes the process for submitting pull requests.
