import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    /**
     * http://tools.android.com */
    const val constraint_layout: String = "com.android.support.constraint:constraint-layout:" +
        Versions.constraint_layout

    /**
     * https://developer.android.com/testing */
    const val espresso_core: String = "com.android.support.test.espresso:espresso-core:" +
        Versions.espresso_core

    /**
     * https://developer.android.com/testing */
    const val com_android_support_test_runner: String = "com.android.support.test:runner:" +
        Versions.com_android_support_test_runner

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val appcompat_v7: String = "com.android.support:appcompat-v7:" + Versions.appcompat_v7

    /**
     * https://developer.android.com/studio */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * https://developer.android.com/studio */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
        Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/studio */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * http://github.com/KeepSafe/dexcount-gradle-plugin/ */
    const val dexcount_gradle_plugin: String = "com.getkeepsafe.dexcount:dexcount-gradle-plugin:" +
        Versions.dexcount_gradle_plugin

    const val play_publisher: String = "com.github.triplet.gradle:play-publisher:" +
        Versions.play_publisher

    const val com_gradle_build_scan_gradle_plugin: String =
        "com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:" +
            Versions.com_gradle_build_scan_gradle_plugin

    const val com_jfrog_artifactory_gradle_plugin: String =
        "com.jfrog.artifactory:com.jfrog.artifactory.gradle.plugin:" +
            Versions.com_jfrog_artifactory_gradle_plugin

    /**
     * https://github.com/square/moshi */
    const val moshi: String = "com.squareup.moshi:moshi:" + Versions.moshi

    /**
     * https://github.com/square/okhttp */
    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
        Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/okhttp */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.com_squareup_okhttp3

    const val de_fayard_buildsrcversions_gradle_plugin: String =
        "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val io_fabric_tools_gradle: String = "io.fabric.tools:gradle:" +
        Versions.io_fabric_tools_gradle

    /**
     * https://github.com/ReactiveX/RxJava */
    const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

    /**
     * http://junit.org */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * https://github.com/ajoberstar/gradle-git */
    const val gradle_git: String = "org.ajoberstar:gradle-git:" + Versions.gradle_git

    const val org_gradle_kotlin_kotlin_dsl_gradle_plugin: String =
        "org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:" +
            Versions.org_gradle_kotlin_kotlin_dsl_gradle_plugin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_android_extensions: String =
        "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
        Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_sam_with_receiver: String = "org.jetbrains.kotlin:kotlin-sam-with-receiver:" +
        Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_scripting_compiler_embeddable: String =
        "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
        Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
        Versions.org_jetbrains_kotlin
}
