include::doc/includes.adoc[]

:toc: right


= buildSrcVersions

{badge_mit} {badge_version} {badge_issues} {badge_pr} {badge_build}

This Gradle plugin adds a **:buildSrcVersions** task to your build that

- Extract automatically all your Gradle dependencies to {root}/buildSrc/src/main/kotlin/Versions.kt[buildSrc/src/main/kotlin/Versions.kt].
- Inform you about available updates inside {root}/buildSrc/src/main/kotlin/Versions.kt[buildSrc/src/main/kotlin/Versions.kt].






== Extract your dependencies


```bash
$ ./gradlew buildSrcVersions
> Task :dependencyUpdates
> Task :buildSrcVersions
        new file:   buildSrc/build.gradle.kts
        new file:   buildSrc/.gitignore
        new file:   buildSrc/settings.gradle.kts
        new file:   buildSrc/src/main/kotlin/Libs.kt
        new file:   buildSrc/src/main/kotlin/Versions.kt
```


== IDE integration

TODO: screencast



```kotlin
dependencies {
    implementation(Libs.okio)
    implementation(Libs.com_squareup_moshi_moshi)
    implementation(Libs.retrofit)
}
```



== Update your dependencies

```bash
$ ./gradlew buildSrcVersions
> Task :dependencyUpdates
> Task :buildSrcVersions
        modified:   buildSrc/src/main/kotlin/Libs.kt
        modified:   buildSrc/src/main/kotlin/Versions.kt

```

TODO: screencast

== Prerequisites

- Kotlin, JVM and Android projects.
- Gradle 4.1+ and Gradle 5.0+
- The IDE integration works:
    - for both `build.gradle` (Groovy) and `build.gradle.kts` (Kotlin) files.
    - in IntelliJ >= 2008.03+ and Android Studio 3.2+.

== Installation

Edit your root `build.gradle(.kts)` file

[source,kotlin,subs=attributes]
----
buildscript {
    //...
}
plugins {
  id("jmfayard.github.io.gradle-kotlin-dsl-libs") version "{plugin_version}"
}
// Don't put any code before the buildscripts {} and plugins {} block
----


== Changelog

See https://github.com/jmfayard/gradle-kotlin-dsl-libs/blob/master/CHANGELOG.md[CHANGELOG.md]

//== Contributors
//
//include::doc/contributors.adoc[]

== Contributing

- This project is licensed under the MIT License - see the [LICENSE.md](LICENSE.md) file for details
- Explain your use case and start the discussion before your submit a pull-request
- Run the automated tests with
- Format your code

Please read [CONTRIBUTING.md](https://gist.github.com/PurpleBooth/b24679402957c63ec426) for details on our code of conduct, and the process for submitting pull requests to us.


== Acknowledgments

This project sits on the shoulder of giants:

