import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Versions {
    /**
     * [gradle website](https://developer.android.com/studio) */
    const val com_android_tools_build_gradle: String =
        "3.2.1" // available milestone: "3.3.0-alpha13"

    /**
     * [firebase-database website](https://github.com/b3er/RxFirebase2) */
    const val com_github_b3er_rxfirebase_firebase_database: String = "11.2.0" // up-to-date

    /**
     * [compiler website](https://github.com/bumptech/glide) */
    const val com_github_bumptech_glide_compiler: String = "4.8.0" // up-to-date

    const val com_google_firebase_firebase_database: String =
        "12.0.0" // available milestone: "16.0.3"

    const val io_fabric_tools_gradle: String = "1.26.1" // up-to-date

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
        "0.2.4" // up-to-date

    /**
     * [kotlin-scripting-compiler-embeddable website](https://kotlinlang.org/) */
    const val kotlin_scripting_compiler_embeddable: String = "1.2.71" // up-to-date

    const val krangl: String = "0.10.3" // up-to-date

    /**
     * [okio website](https://github.com/square/okio/) */
    const val okio: String = "2.0.0" // available milestone: "2.1.0"

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String = "1.2.71" // up-to-date

    /**
     * [rxjava website](https://github.com/ReactiveX/RxJava) */
    const val rxjava: String = "2.2.0" // available milestone: "2.2.2" 

    /**
     *
     *   To update Gradle, edit the wrapper file at path:
     *      ./gradle/wrapper/gradle-wrapper.properties
     */
    object Gradle {
        const val runningVersion: String = "4.10.2"

        const val currentVersion: String = "4.10.2"

        const val nightlyVersion: String = "5.1-20181015235836+0000"

        const val releaseCandidate: String = ""
    }
}
