package de.fayard.buildSrcLibs.internal

import de.fayard.buildSrcLibs.BuildSrcTask
import de.fayard.refreshVersions.core.RefreshVersionsTask


@Suppress("unused")
internal object PluginConfig {

    /** Documentation **/
    internal fun issue(number: Int): String = "$refreshVersionsUrl/issues/$number"

    const val refreshVersionsUrl = "https://github.com/jmfayard/refreshVersions"

    val INITIAL_GITIGNORE = """
        |.gradle/
        |build/
        """.trimMargin()

    val KDOC_LIBS = """
        |Generated by
        |   $ ./gradlew ${BuildSrcTask.TASK_NAME_buildSrcLibs}
        |Re-run when you add a new dependency to the build
        |
        |Find which updates are available by running
        |    $ ./gradlew ${RefreshVersionsTask.TASK_NAME}
        |And edit the file `versions.properties`
        |
        |See $refreshVersionsUrl
    """.trimMargin()

    //
    val KDOC_VERSIONS = """

        |And edit the file `versions.properties`

    """.trimMargin()


    val INITIAL_BUILD_GRADLE_KTS = """
        |plugins {
        |    `kotlin-dsl`
        |}
        |repositories {
        |    mavenCentral()
        |}
        """.trimMargin()


}
