package de.fayard.refreshVersions

import de.fayard.refreshVersions.core.ModuleId.Maven
import de.fayard.refreshVersions.core.RefreshVersionsCorePlugin

internal data class DependenciesDocGenerator(
    val mavenDependenciesInBuild: List<Maven>
) {

    internal companion object {
        fun hardCoded() = listOf(
            Maven("com.squareup.sqldelight", "coroutines-extensions"),
            Maven("io.kotest", "kotest-core")
        )
    }

    fun generateMarkdown(dependenciesAndDocs: List<DependencyAndDoc>): String {
        return """
${DependencyAndDoc.MARKDOWN_INTRO}

${dependenciesAndDocs.joinToString { it.markdown() }}
        """.trimIndent()
    }

    fun dependenciesAndDocs(): List<DependencyAndDoc> {
        val (mavenSquare, mavenKotest) = hardCoded()
        val square = DependencyAndDoc(
            maven = mavenSquare,
            kotlinName = "Square.sqlDelight.extensions.coroutines",
            versionName = "version.sqldlight",
            kdoc = "todo",
            changelogUrl = "https://github.com/cashapp/sqldelight/blob/master/CHANGELOG.md"
        )
        val kotest = DependencyAndDoc(
            maven = mavenKotest,
            kotlinName = "Testing.kotest.core",
            versionName = "version.kotest",
            kdoc = "todo",
            changelogUrl = "https://kotest.io/docs/changelog.html"
        )
        return listOf(square, kotest)
    }

    fun updateChangeLogsUrlsInFiles(changeLogUrls: List<DependencyAndDoc>) {
        println("## updateChangeLogsUrlsInFiles()")
        println(changeLogUrls.joinToString("\n"))
        println("well I'm not doing anything for now")
    }
}

internal data class DependencyAndDoc(
    val maven: Maven,
    val kotlinName: String,
    val versionName: String,
    val kdoc: String,
    val changelogUrl: String,
) {
    fun markdown() = """

        ## $kotlinName

        - maven:        "${maven.group}:${maven.name}"
        - kotlinName:   $kotlinName
        - versionName:  $versionName
        - changelogUrl: $changelogUrl

        $kdoc

    """.trimIndent()

    companion object {
        val MARKDOWN_INTRO = """
# Dependencies documentation

Generated by `./gradlew ${RefreshDependenciesDocTask.TASK_NAME}` from ${RefreshVersionsCorePlugin.refreshVersionsUrl}

    """.trimIndent()
    }
}
