import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {
    const val clikt: String = "com.github.ajalt.clikt:clikt:_"

    const val okio: String = "com.github.javadev:okio:_"

    const val mockito_kotlin: String = "com.nhaarman.mockitokotlin2:mockito-kotlin:_"

    const val okhttp: String = "com.squareup.okhttp3:okhttp:_"

    const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    const val kotest_assertions_core: String = "io.kotest:kotest-assertions-core:_"

    const val kotest_assertions_json: String = "io.kotest:kotest-assertions-json:_"

    const val kotest_assertions_jsoup: String = "io.kotest:kotest-assertions-jsoup:_"

    const val kotest_assertions_sql: String = "io.kotest:kotest-assertions-sql:_"

    const val kotest_core: String = "io.kotest:kotest-core:_"

    const val kotest_extensions_http: String = "io.kotest:kotest-extensions-http:_"

    const val kotest_extensions_koin: String = "io.kotest:kotest-extensions-koin:_"

    const val kotest_extensions_mockserver: String = "io.kotest:kotest-extensions-mockserver:_"

    const val kotest_plugins_pitest: String = "io.kotest:kotest-plugins-pitest:_"

    const val kotest_property: String = "io.kotest:kotest-property:_"

    const val kotest_runner_junit4: String = "io.kotest:kotest-runner-junit4:_"

    const val ktor_auth: String = "io.ktor:ktor-auth:_"

    const val ktor_client_auth: String = "io.ktor:ktor-client-auth:_"

    const val ktor_client_auth_basic: String = "io.ktor:ktor-client-auth-basic:_"

    const val ktor_client_cio: String = "io.ktor:ktor-client-cio:_"

    const val ktor_client_core: String = "io.ktor:ktor-client-core:_"

    const val ktor_client_encoding: String = "io.ktor:ktor-client-encoding:_"

    const val ktor_client_json: String = "io.ktor:ktor-client-json:_"

    const val ktor_client_logging: String = "io.ktor:ktor-client-logging:_"

    const val ktor_client_okhttp: String = "io.ktor:ktor-client-okhttp:_"

    const val ktor_client_serialization: String = "io.ktor:ktor-client-serialization:_"

    const val ktor_client_websockets: String = "io.ktor:ktor-client-websockets:_"

    const val ktor_html_builder: String = "io.ktor:ktor-html-builder:_"

    const val ktor_http: String = "io.ktor:ktor-http:_"

    const val ktor_network: String = "io.ktor:ktor-network:_"

    const val ktor_network_tls: String = "io.ktor:ktor-network-tls:_"

    const val ktor_server_core: String = "io.ktor:ktor-server-core:_"

    const val ktor_utils: String = "io.ktor:ktor-utils:_"

    const val mockk: String = "io.mockk:mockk:_"

    const val mockk_common: String = "io.mockk:mockk-common:_"

    const val junit: String = "junit:junit:_"

    const val org_gradle_hello_world_gradle_plugin: String =
            "org.gradle.hello-world:org.gradle.hello-world.gradle.plugin:_"

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:_"

    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:_"

    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib"

    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    const val junit_jupiter: String = "org.junit.jupiter:junit-jupiter:_"

    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:_"

    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:_"

    const val junit_jupiter_params: String = "org.junit.jupiter:junit-jupiter-params:_"

    const val mockito_core: String = "org.mockito:mockito-core:_"

    const val mockito_errorprone: String = "org.mockito:mockito-errorprone:_"

    const val mockito_inline: String = "org.mockito:mockito-inline:_"

    const val mockito_junit_jupiter: String = "org.mockito:mockito-junit-jupiter:_"
}
