import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import de.fayard.VersionsOnlyMode

plugins {
    kotlin("jvm") version "1.3.50"
    id("de.fayard.buildSrcVersions") version "0.4.3"
}

group = "de.fayard"




repositories {
    mavenCentral()
}

dependencies {
    // <buildSrcVersions>
    // Generated by ./gradle buildSrcVersions
    // See https://github.com/jmfayard/buildSrcVersions/issues/54
    val okhttp = "4.1.0"
    val okio = "2.0.0"
    val org_jetbrains_kotlin_jvm_gradle_plugin = "1.3.50"
    val org_jetbrains_kotlin = "1.3.50"
    // </buildSrcVersions>

    implementation(kotlin("stdlib-jdk8", org_jetbrains_kotlin))

    implementation("com.squareup.okhttp3:okhttp:$okhttp")
    implementation("com.squareup.okio:okio:$okio")
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}


buildSrcVersions {
    indent = "\t"
    versionsOnlyMode = VersionsOnlyMode.KOTLIN_VAL
    versionsOnlyFile = "build.gradle.kts"
}
