// versionOnlyMode = KOTLIN_VAL

// <buildSrcVersions>
// Generated by ./gradle buildSrcVersions
// See https://github.com/jmfayard/buildSrcVersions/issues/54
val org_jetbrains_kotlin_jvm_gradle_plugin = "1.3.50"
val gradleCurrentVersion = "5.5.1"
val org_jetbrains_kotlin = "1.3.50"
val gradleLatestVersion = "5.6.1"
val okhttp = "4.1.0" // available: "4.1.1"
val okio = "2.0.0"
// </buildSrcVersions>


// versionOnlyMode = KOTLIN_VAL
