// versionOnlyMode = KOTLIN_VAL

// <buildSrcVersions>
// Generated by ./gradle buildSrcVersions
// See https://github.com/jmfayard/buildSrcVersions/issues/54
val org_lovedev_greeting_kotlin_gradle_plugin = "1.1"
val org_jetbrains_kotlin_jvm_gradle_plugin = "1.3.50"
val ch_tutteli_kotlin_utils_gradle_plugin = "0.29.0"
val com_gradle_build_scan_gradle_plugin = "2.4.1" // available: "2.4.2"
val nebula_kotlin_gradle_plugin = "1.3.50"
val gradleCurrentVersion = "5.6.2"
val org_jetbrains_kotlin = "1.3.50"
val gradleLatestVersion = "5.6.2"
val guava = "15.0" // available: "23.0"
val guice = "2.0" // available: "4.2.2"
// </buildSrcVersions>


// versionOnlyMode = KOTLIN_VAL
