// versionOnlyMode = KOTLIN_VAL

// <buildSrcVersions>
// Generated by ./gradle buildSrcVersions
// See https://github.com/jmfayard/buildSrcVersions/issues/54
val org_jetbrains_kotlin_jvm_gradle_plugin = "1.3.50"
val kotlin_scripting_compiler_embeddable = "1.3.50"
val gradleCurrentVersion = "5.6.2"
val gradleLatestVersion = "5.6.2"
val guava = "15.0" // available: "23.0"
val guice = "2.0" // available: "4.2.2"
// </buildSrcVersions>


// versionOnlyMode = KOTLIN_VAL
