name: Build MkDocs website as artifacts
on:
  push:
    branches-ignore:
      - release
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'CHANGELOG.md'
      # Any additional files/dirs that take part in updating the website must be added here.
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: ./docs/DocsCopier.main.kts
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r docs/requirements.txt
      - run: mkdocs build --site-dir public
      - uses: actions/upload-artifact@v4
        with:
          name: docs-static-website
          path: public
