name: mkdocs
on:
  push:
    branches:
      - master
      - mkdocs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: sh docs/before-publish.sh
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --force
