# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Publish plugins
on:
  workflow_dispatch:
  pull_request:
    types: [opened]
    paths:
      - 'plugins/version.txt'
    branches:
      - release
jobs:
  gradle-plugins-publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-executable: plugins/gradlew
          build-root-directory: plugins
          arguments: publishPlugins --scan -Pgradle.publish.key=${{ secrets.gradle_publish_key }} -Pgradle.publish.secret=${{ secrets.gradle_publish_secret }}
        env:
          sonatype_username: ${{ secrets.SONATYPE_USERNAME }}
          sonatype_password: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_key_id: ${{ secrets.GPG_KEY_ID }}
          GPG_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_private_password: ${{ secrets.GPG_PRIVATE_PASSWORD }}
